### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by andrewda**
I was confused about what this repository was for. This README should clear some things up ❤️ 💅 🎈 🎉

### CODE REVIEW

**Comment by will-hou** [comment]
Hmmm I still don't know what the repository is for but it'll do I suppose...







😛 Thanks for makin' this for us

**Review by will-hou — APPROVED** [review]

**Comment by gnawinganimal** [comment]
Wait, this is our BunnyBots code? I didn't even realize that before I read this README.

**Review by gnawinganimal — APPROVED** [review]

**Comment by mckelveygreg** [comment]
_(These would be good types of PRs to help people new to git and github...)_

**Comment by andrewda** [comment]
@mckelveygreg good point! Added a few more good first issues to the issue list.

**Pull request merged**
